server:
  port: 8000

spring:
  application:
    name: apigateway-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    config:
      name: secret
    gateway:
      routes:
        # user-service routing
        # Jwt Filter Not Necessary (login, join)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/**
            - Method=POST
          filters:
              # Not using Cookie
            - RemoveRequestHeader=Cookie
              # Url Path : localhost:8080/user-service/api/v1 => localhost:8080/api/v1
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # (refresh token request)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/refresh
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # (Oauth2 Login)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/oauth2/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}


        ################
        # Jwt Filter Necessary (etc...)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/v1/members/**
            - Method=GET,POST,PUT,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - JwtFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # Til-service Routing
        # (board Service)
        - id: til-service
          uri: lb://TIL-SERVICE
          predicates:
            - Path=/til-service/api/v1/boards/**
            - Method=GET, POST, PUT, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - JwtFilter
            - RewritePath=/til-service/(?<segment>.*), /$\{segment}

        # (image Service)
        - id: til-service
          uri: lb://TIL-SERVICE
          predicates:
            - Path=/til-service/api/v1/images/**
            - Method=GET, POST, PUT, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
#            - JwtFilter
            - RewritePath=/til-service/(?<segment>.*), /$\{segment}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka