server:
  port: 8084

spring:
  application:
    name: tag-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    config:
      name: secret

logging:
  level:
    propofol:
      tagservice: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka