server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cl8D/propofol-service.git

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"